### ISSUE TITLE
Release with the less-loader compat fix.

### ISSUE THREAD

**Issue by atractom** [wuzekang/antd-theme#1]
If it is not too much trouble, could you please push to npm including " fix: compatible with less-loader@5 and less-loader@6 " as we have been hitting the infamous "Less Loader has been initialized using an options object that does not match the API schema." but would  ideally like to try this too compared to antd-theme-webpack-plugin?
FYI building/running `site` locally from master works fine and looks good - thank you for sharing this.

**Comment by wuzekang** [comment]
Thank you for your reminder, the new version has been released to npm

**Comment by wuzekang** [comment]
If you have other questions, feel free to open a new issue
