### ISSUE TITLE
there is a problem with running the site project

### ISSUE THREAD

**Issue by dxiongya** [wuzekang/antd-theme#15]
I just :
1. clone project 
2. npm install 
3. npm start

but there is an error：
1. Error evaluating function `if`: Cannot read property 'eval' of undefined
2. Variable @heading-color-dark is undefined

What should i do？

**Comment by akramer24** [comment]
I've encountered this as well

**Comment by AlisaBen** [comment]
+1

**Comment by wuzekang** [comment]
#20
